from typing import Protocol, AsyncIterator
from .models import AudioObservation, AudioStatus

class AudioFrontEnd(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def status(self) -> AudioStatus: ...
    def observations(self) -> AsyncIterator[AudioObservation]: ...
