import React,{useCallback,useEffect,useRef,useState} from 'react';
import {Activity,ArrowLeft,ArrowRight,AudioLines,Camera,Check,ChevronRight,Circle,Clapperboard,Command,Eye,Hand,HelpCircle,LayoutDashboard,Maximize2,Mic,Monitor,MonitorOff,MoreHorizontal,Play,Power,Radio,RefreshCw,Settings,ShieldCheck,SlidersHorizontal,Sparkles,Square,Video,Volume2,VolumeX,WifiOff,X} from 'lucide-react';
import type {InstructorAppState,Mode,Preferences} from './types';
import './styles.css';
const API='http://localhost:8000';
const modes:Mode[]=['off','assist','auto'];
const explanations={off:'You control the room.',assist:'AI suggests changes. You choose what to apply.',auto:'AI handles routine changes. You can always step in.'};
const friendlyStatus={ready:'Ready',degraded:'Degraded',disconnected:'Disconnected',connecting:'Connecting'};
const framing=[['presenter','Presenter'],['demo_zone','Demo area'],['wide','Wide']];
const sources=[['presentation','Laptop'],['room_pc','Room PC'],['camera','Program'],['blank','Blank']];
const layouts=[['slides_plus_instructor','Slides + presenter'],['demo_primary','Demonstration'],['media_primary','Media'],['wide','Wide']];
async function api(path:string,method='GET',body?:unknown){
 const response=await fetch(API+path,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
 if(!response.ok){let message='That change could not be confirmed. Please try again.';try{const data=await response.json();if(typeof data.detail==='string')message=data.detail}catch{}throw new Error(message)}
 return response.json();
}
function Dot({status='ready'}:{status?:string}){return <span className={'status-dot '+status}/>}
function elapsed(start:string|null){if(!start)return '00:00';const total=Math.max(0,Math.floor((Date.now()-Date.parse(start))/1000));return [Math.floor(total/3600),Math.floor(total/60)%60,total%60].map(n=>String(n).padStart(2,'0')).join(':')}
function Toggle({on,onClick,disabled=false,label}:{on:boolean;onClick:()=>void;disabled?:boolean;label:string}){return <button className={'switch '+(on?'on':'')} aria-label={label} role="switch" aria-checked={on} onClick={onClick} disabled={disabled}><span/></button>}
function ProgramPreview({state}:{state:InstructorAppState}){
 const layout=state.programState.layout;const unavailable=state.programState.preview.kind==='unavailable';
 return <div className={'program-preview '+(layout||'unavailable')}>
  <div className="preview-top"><span><span className="tiny-square"/> PROGRAM OUTPUT</span><span>{state.programState.label}</span></div>
  {unavailable?<div className="preview-offline"><Video size={38}/><h3>Program preview unavailable</h3><p>Your room display can still work independently.</p></div>:<div className="composition">
   {(layout==='slides_plus_instructor'||layout==='media_primary')&&<div className="presentation-frame"><div className="slide-label">{layout==='media_primary'?'PROGRAM MEDIA':'PRESENTATION'}</div>{layout==='media_primary'?<div className="media-placeholder"><Play size={35}/><span>Media composition</span></div>:<><h2>A space<br/>for ideas.</h2><div className="slide-rule"/><p>Instructor presentation</p><span className="slide-number">01 / 03</span></>}</div>}
   {layout!=='media_primary'&&<div className="camera-frame"><div className="camera-frame-label"><Camera size={13}/>{layout==='demo_primary'?'Demo area':state.cameraState.label}</div><svg viewBox="0 0 260 190" aria-label="Illustrated camera framing" role="img"><defs><linearGradient id="roomwall" x2="0" y2="1"><stop stopColor="#526560"/><stop offset="1" stopColor="#2c3e39"/></linearGradient></defs><rect width="260" height="190" fill="url(#roomwall)"/><path d="M0 140H260V190H0Z" fill="#25362f"/><rect x="30" y="26" width="200" height="84" rx="2" fill="#83958b" opacity=".4"/>{layout==='demo_primary'||state.cameraState.target==='demo_zone'?<><rect x="45" y="113" width="170" height="12" fill="#c8bfa7"/><path d="M60 125V180M200 125V180" stroke="#92a89b" strokeWidth="7"/><path d="M104 112V80L125 62L146 80V112Z" fill="#c2ceb7"/></>:<><circle cx="130" cy="83" r="18" fill="#b6c3ad"/><path d="M91 166V132Q94 107 130 107Q166 107 169 132V166Z" fill="#bdc9b6"/><path d="M80 155H180V172H80Z" fill="#1b3028"/></>}</svg><span className="framing-caption">{layout==='demo_primary'?'Demonstration framing':state.cameraState.label+' framing'}</span></div>}
  </div>}
  <div className="preview-bottom"><span><Eye size={13}/>{state.programState.preview.description}</span><span>{state.recordingState.recording?<><i className="rec-dot"/> RECORDING</>:'NOT RECORDING'}</span></div>
 </div>
}

export default function InstructorApp(){
 const initial=location.pathname==='/devices'?'devices':location.pathname==='/settings'?'settings':location.pathname==='/dev'?'diagnostics':'room';
 const [page,setPage]=useState(initial);const [state,setState]=useState<InstructorAppState|null>(null);const [connected,setConnected]=useState(true);
 const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [takingControl,setTakingControl]=useState(false);const [why,setWhy]=useState(false);
 const [prefs,setPrefs]=useState<Preferences|null>(null);const [saved,setSaved]=useState(false);const [diagnostics,setDiagnostics]=useState<any>(null);const [settingsSection,setSettingsSection]=useState('AI');
 const [expanded,setExpanded]=useState(false);const mounted=useRef(true);const request=useRef(0);
 const refresh=useCallback(async()=>{const n=++request.current;try{const data=await api('/api/instructor/state');if(mounted.current&&n===request.current){setState(data);setConnected(true)}}catch{if(mounted.current&&n===request.current)setConnected(false)}},[]);
 useEffect(()=>{mounted.current=true;refresh();const timer=setInterval(refresh,1000);return()=>{mounted.current=false;clearInterval(timer)}},[refresh]);
 const navigate=(next:string)=>{setPage(next);history.pushState({},'',next==='room'?'/':next==='diagnostics'?'/dev':'/'+next)};
 useEffect(()=>{const listener=()=>setPage(location.pathname==='/devices'?'devices':location.pathname==='/settings'?'settings':location.pathname==='/dev'?'diagnostics':'room');window.addEventListener('popstate',listener);return()=>window.removeEventListener('popstate',listener)},[]);
 useEffect(()=>{if(page==='settings')api('/api/instructor/settings').then(setPrefs).catch(e=>setError(e.message));if(page==='diagnostics')api('/api/instructor/diagnostics').then(setDiagnostics).catch(e=>setError(e.message))},[page]);
 const run=async(path:string,body?:unknown,method='POST')=>{setBusy(true);setError('');try{await api(path,method,body);await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const action=(tool:string,args:Record<string,unknown>={})=>run('/api/instructor/action',{tool,args});
 const takeControl=async()=>{setTakingControl(true);try{await api('/api/instructor/take-control','POST');setError('');await refresh()}catch(e:any){setError(e.message)}finally{setTakingControl(false)}};
 if(!state)return <div className="connecting-screen"><div className="brand-symbol"><Command/></div><h1>Agentic Classroom</h1><p>{connected?'Getting your room ready…':'The room controller is offline.'}</p><button onClick={refresh}>Reconnect</button></div>;
 const disable=busy||!connected;const mode=state.aiMode;const recent=state.recentActions[0];const recording=state.recordingState.recording;const videoReady=state.recordingState.status==='ready';
 const navItems=[{id:'room',label:'Classroom',icon:LayoutDashboard},{id:'devices',label:'Devices',icon:Radio},{id:'settings',label:'Settings',icon:Settings}];
 const sourceName=state.currentDisplay.available?state.currentDisplay.label:'Status unavailable';
 return <div className="product-shell">
  <aside className="sidebar"><a className="brand-symbol" href="/" aria-label="Agentic Classroom home"><Command size={25}/></a><nav>{navItems.map(({id,label,icon:Icon})=><button title={label} aria-label={label} aria-current={page===id?'page':undefined} className={page===id?'active':''} key={id} onClick={()=>navigate(id)}><Icon size={21}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><span className="local-dot"/><span>LOCAL</span></div></aside>
  <div className="workspace"><header className="app-header"><div className="wordmark">Agentic Classroom<span>CLASSROOM CONTROL</span></div><div className="header-status"><span><Dot status={!connected?'disconnected':state.roomStatus}/>{!connected?'Controller offline':state.roomStatus==='ready'?'Room ready':'Room degraded'}</span><span><Dot status={state.ai.status}/>{state.ai.label} · {state.ai.status==='ready'?'Online':state.ai.status==='connecting'?'Connecting':'Offline'}</span><span className={recording?'recording-live':''}><Circle size={10} fill={recording?'currentColor':'none'}/>{recording?'REC '+elapsed(state.recordingState.startedAt):recording===null?'Recording unknown':'Not recording'}</span></div></header>
   <main>
    {!connected&&<div className="alert" role="alert"><WifiOff size={18}/><span>Connection lost. Displayed state may be out of date. Controls reconnect automatically.</span><button onClick={refresh}>Retry</button></div>}
    {error&&<div className="alert" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss message"><X size={18}/></button></div>}
    {page==='room'&&<>
     <div className="page-heading"><div><p className="eyebrow">YOUR CLASSROOM</p><h1>{state.roomStatus==='ready'?'Ready for your next idea.':'Let’s get your room ready.'}</h1><p>Everything you need to keep teaching.</p></div><div className="mode-control"><span>AI MODE <HelpCircle size={13}/></span><div role="group" aria-label="AI Mode">{modes.map(m=><button key={m} disabled={!connected} aria-pressed={mode===m} className={mode===m?'selected':''} onClick={()=>run('/api/instructor/mode',{mode:m})}>{m==='off'?<Power size={15}/>:<Sparkles size={15}/>}<span>{m[0].toUpperCase()+m.slice(1)}</span></button>)}</div><small>{explanations[mode]}</small></div></div>
     <div className="main-grid"><div className="primary-column">
      <section className={'preview-card '+(expanded?'expanded-preview':'')}><div className="section-heading"><div><Video size={18}/><h2>Recording / program</h2></div><span className="preview-context">Now · {state.currentActivity}</span><button className="icon-button" onClick={()=>setExpanded(!expanded)} aria-label={expanded?'Shrink preview':'Expand preview'}><Maximize2 size={16}/></button></div><ProgramPreview state={state}/><div className="preview-footer"><span><Clapperboard size={16}/>{state.programState.label}</span><select aria-label="Program layout" value={state.programState.layout||''} disabled={disable||!videoReady} onChange={e=>action('recording_set_layout',{layout:e.target.value})}>{!state.programState.layout&&<option value="">Unavailable</option>}{layouts.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div></section>
      <section className="now-card"><div className="now-title"><span className="icon-tile"><Activity size={20}/></span><div><p className="eyebrow">NOW</p><h2>{state.currentActivity}</h2></div><span className="live-tag">{state.currentActivity==='Watching…'?'Observing':'Current context'}</span></div><div className="context-details"><span><Monitor size={16}/>{state.currentDisplay.available?state.currentDisplay.source==='blank'?'Room display is blank':state.currentDisplay.label+' on display':'Display status unavailable'}</span><span><Mic size={16}/>{state.audioState.microphoneActive?'Presenter speaking':'Microphone quiet'}</span><span><Camera size={16}/>{state.cameraState.available?state.cameraState.follow?'Following presenter':'Camera: '+state.cameraState.label:'Camera disconnected'}</span></div></section>
      <section className={'assistant-card '+(state.pendingRecommendation?'has-suggestion':'')}><div className="assistant-icon"><Sparkles size={22}/></div><div className="assistant-content"><div className="assistant-heading"><h2>{state.ai.busy?'Checking the room…':state.pendingRecommendation?'A suggested adjustment':mode==='off'?'You’re in control':mode==='assist'?'A helping hand, when you need it':'Keeping your room in step'}</h2><span>{mode==='off'?'AI OFF':mode.toUpperCase()}</span></div><p>{state.ai.message||(!state.pendingRecommendation?explanations[mode]:state.pendingRecommendation.title)}</p>{state.pendingRecommendation&&<><ul>{state.pendingRecommendation.actions.map((label,i)=><li key={i}><Check size={14}/>{label}</li>)}</ul><div className="suggestion-buttons"><button className="primary-button" disabled={disable} onClick={()=>run('/api/instructor/recommendation/'+state.pendingRecommendation!.id+'/apply')}>Apply changes <ArrowRight size={15}/></button><button className="text-button" disabled={disable} onClick={()=>run('/api/instructor/recommendation/'+state.pendingRecommendation!.id+'/ignore')}>Ignore</button><button className="why-button" onClick={()=>setWhy(!why)}>Why?</button></div>{why&&<p className="why-text">{state.pendingRecommendation.why}</p>}</>}{!state.pendingRecommendation&&mode!=='off'&&!state.ai.busy&&<span className="assistant-note"><ShieldCheck size={14}/>You can change any control at any time.</span>}</div></section>
     </div><div className="controls-column">
      <section className="control-card"><div className="card-heading"><h2><Camera size={18}/>Camera</h2><Dot status={state.cameraState.available?'ready':'disconnected'}/></div><p className="current-value">{state.cameraState.available?state.cameraState.follow?'Following presenter':state.cameraState.label:'Disconnected'}</p><div className="segmented">{framing.map(([target,label])=><button key={target} disabled={disable||!state.cameraState.available} aria-pressed={state.cameraState.target===target||target==='presenter'&&state.cameraState.target==='instructor'} onClick={()=>action('camera_focus',{target})}>{label}</button>)}</div><div className="toggle-row"><span>Follow presenter</span><Toggle label="Follow presenter" on={state.cameraState.follow} disabled={disable||!state.cameraState.available} onClick={()=>action('camera_set_follow',{enabled:!state.cameraState.follow})}/></div></section>
      <section className="control-card"><div className="card-heading"><h2><Monitor size={18}/>Room display</h2><Dot status={state.currentDisplay.available?'ready':'disconnected'}/></div><p className="current-value">{sourceName}</p><div className="source-grid">{sources.map(([source,label],i)=>{const Icon=[Monitor,Command,Video,MonitorOff][i];return <button key={source} disabled={disable||!state.currentDisplay.available} aria-pressed={state.currentDisplay.source===source} onClick={()=>action('display_set_source',{source})}><Icon size={18}/>{label}</button>})}</div><p className="card-note">What the room sees. Separate from your program.</p></section>
      <section className="control-card"><div className="card-heading"><h2><AudioLines size={18}/>Audio</h2><Dot status={state.audioState.available?'ready':'disconnected'}/></div><div className="segmented audio-options">{[['lecture','Presentation'],['media','Media'],['mute','Mute']].map(([audio,label])=><button key={audio} disabled={disable||!state.audioState.available} aria-pressed={state.audioState.mode===audio} onClick={()=>action('audio_set_mode',{mode:audio})}>{audio==='mute'?<VolumeX size={15}/>:<Volume2 size={15}/>} {label}</button>)}</div><div className="audio-indicators"><span><Dot status={state.audioState.microphoneActive?'ready':'idle'}/>Instructor mic</span><span><Dot status={state.audioState.programActive?'ready':'idle'}/>Program audio</span></div></section>
      <section className={'control-card recording-card '+(recording?'is-recording':'')}><div className="card-heading"><h2><Circle size={17}/>Recording</h2><span className="recording-state">{recording?<><i className="rec-dot"/> {elapsed(state.recordingState.startedAt)}</>:recording===null?'Unknown':'Off'}</span></div><p>{recording===null?'Reconnect the video engine to check recording.':state.recordingState.simulated?'Practice recording · no video file is saved.':recording?'Recording your program composition.':'Start only when you’re ready.'}</p><button className={'record-button '+(recording?'stop':'')} disabled={disable||!videoReady} onClick={()=>action(recording?'recording_stop':'recording_start')}>{recording?<Square size={14} fill="currentColor"/>:<Circle size={14} fill="currentColor"/>}{recording?'Stop recording':'Start recording'}</button></section>
     </div></div>
     <section className="recent-section"><div className="section-heading"><div><Activity size={16}/><h2>Recent activity</h2></div><span>Only the changes that matter</span></div>{state.recentActions.length===0?<p className="empty-history">Your room is ready. Changes will appear here as you teach.</p>:<div className="recent-list">{state.recentActions.slice(0,4).map(event=><div className="recent-row" key={event.id}><span className={'event-icon '+event.actor}>{event.actor==='ai'?<Sparkles size={14}/>:<Hand size={14}/>}</span><time>{new Date(event.time).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</time><span>{event.label}</span><small>{event.actor==='ai'?'AI':event.actor==='approved'?'Approved by you':event.actor==='system'?'Room':'You'}</small>{event.canUndo&&<button className="text-button" disabled={disable} onClick={()=>run('/api/instructor/undo',{action_id:event.id})}>Undo</button>}</div>)}</div>}</section>
    </>}
    {page==='devices'&&<><div className="page-heading"><div><p className="eyebrow">ROOM CONNECTIONS</p><h1>Your room connections.</h1><p>A clear view of what’s ready and what needs attention.</p></div><button className="secondary-button" onClick={refresh}><RefreshCw size={16}/>Refresh status</button></div><div className="devices-grid">{state.devices.map(d=><section className="device-card" key={d.id}><div className="device-symbol">{d.id==='ai'?<Sparkles/>:d.id.includes('camera')?<Camera/>:d.id.includes('audio')?<Mic/>:d.id==='recorder'?<Video/>:<Monitor/>}</div><h2>{d.label}</h2><p>{d.detail}</p><span className={'device-status '+d.status}><Dot status={d.status}/>{friendlyStatus[d.status]}</span></section>)}</div><div className="info-note"><ShieldCheck size={19}/><p>Manual room controls work independently of local AI. A disconnected video engine does not stop the room display.</p></div></>}
    {page==='settings'&&<><div className="page-heading"><div><p className="eyebrow">MAKE IT YOURS</p><h1>Room settings.</h1><p>Simple defaults for a smoother start.</p></div></div><div className="settings-layout"><nav className="settings-nav">{['AI','Camera','Audio','Display','Recording','Devices','Advanced'].map(section=><button className={settingsSection===section?'active':''} key={section} onClick={()=>{setSettingsSection(section);setSaved(false)}}>{section}<ChevronRight size={15}/></button>)}</nav><section className="settings-panel"><h2>{settingsSection}</h2>{prefs&&<>
     {settingsSection==='AI'&&<><label>Default AI mode<select value={prefs.default_mode} onChange={e=>setPrefs({...prefs,default_mode:e.target.value as Mode})}>{modes.map(m=><option key={m} value={m}>{m[0].toUpperCase()+m.slice(1)}</option>)}</select><small>Used the next time the room controller starts.</small></label><label>Local model<input value={prefs.local_model} onChange={e=>setPrefs({...prefs,local_model:e.target.value})}/><small>Must already be installed locally. Changing the model clears pending suggestions.</small></label></>}
     {settingsSection==='Camera'&&<><label>Default framing<select value={prefs.default_framing} onChange={e=>setPrefs({...prefs,default_framing:e.target.value})}>{framing.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><div className="toggle-row"><span>Follow presenter at startup</span><Toggle label="Default follow presenter" on={prefs.follow_presenter} onClick={()=>setPrefs({...prefs,follow_presenter:!prefs.follow_presenter})}/></div><div className="setting-info"><h3>Demo area</h3><p>Demo framing is available as a room preset. Physical camera calibration will be configured when a camera adapter is connected.</p></div></>}
     {settingsSection==='Audio'&&<><div className="setting-info"><h3>Instructor microphone</h3><p>XVF3800 is the room’s audio front end. The current input appears in Devices.</p><h3>Speech detection</h3><p>Device selection and measured speech thresholds are currently configured locally by the room technician. Automatic calibration is not available yet.</p></div><button className="secondary-button" onClick={()=>navigate('devices')}>View audio device<ArrowRight size={15}/></button></>}
     {settingsSection==='Display'&&<><div className="setting-info"><h3>Presentation input</h3><p>Instructor laptop uses the presentation input. Room PC and Camera / program can be selected from the classroom dashboard.</p><h3>Program output</h3><p>The video engine’s composition is separate from the room display. Physical input/output mapping will be configured with the display adapter.</p></div></>}
     {settingsSection==='Recording'&&<><label>Default program layout<select value={prefs.default_layout} onChange={e=>setPrefs({...prefs,default_layout:e.target.value})}>{layouts.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><div className="setting-info"><h3>Recording destination</h3><p>{state.recordingState.simulated?'Recording is simulated in this room. No video file is written.':'Managed by the connected video engine. OBS is not connected yet.'}</p><p>Starting or stopping a recording is always your choice.</p></div></>}
     {settingsSection==='Devices'&&<><p>Review availability before you begin teaching.</p><button className="secondary-button" onClick={()=>navigate('devices')}>Open Devices<ArrowRight size={15}/></button></>}
     {settingsSection==='Advanced'&&<><div className="setting-info"><h3>Developer diagnostics</h3><p>Inspect the local model, adapter state and normalized observations. These details are not needed for everyday teaching.</p></div><button className="secondary-button" onClick={()=>navigate('diagnostics')}><SlidersHorizontal size={16}/>Open diagnostics</button></>}
     {['AI','Camera','Recording'].includes(settingsSection)&&<div className="settings-save"><button className="primary-button" disabled={disable} onClick={async()=>{setSaved(false);setBusy(true);try{await api('/api/instructor/settings','PUT',prefs);setSaved(true);await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>Save preferences</button>{saved&&<span><Check size={16}/>Saved</span>}<small>Camera and layout defaults apply on the next controller start.</small></div>}
    </>}</section></div></>}
    {page==='diagnostics'&&<><button className="text-button" onClick={()=>{setSettingsSection('Advanced');navigate('settings')}}><ArrowLeft size={15}/>Back to settings</button><div className="page-heading"><div><p className="eyebrow">ADVANCED</p><h1>Developer diagnostics.</h1><p>Local runtime details and development inputs.</p></div><button className="secondary-button" onClick={()=>api('/api/instructor/diagnostics').then(setDiagnostics)}><RefreshCw size={16}/>Refresh</button></div><section className="diagnostics-panel"><h2>Development observations</h2><p>Feed normalized sensor observations through the state engine. These controls are only for development.</p><div className="diagnostic-inputs">{[['v1_lecture','Presentation'],['v1_demonstration','Demo area'],['v1_media_playback','Media playback'],['v1_source_change','Other application']].map(([scenario,label])=><button disabled={disable} key={scenario} onClick={()=>run('/api/scenario/'+scenario)}>{label}</button>)}</div><h2>Runtime</h2><pre>{diagnostics?JSON.stringify(diagnostics,null,2):'Loading diagnostics…'}</pre></section></>}
   </main>
   <footer className="control-bar"><div aria-live="polite"><span className="footer-icon">{state.pendingRecommendation||recent?.actor==='ai'?<Sparkles size={16}/>:<Check size={16}/>}</span>{state.pendingRecommendation?<><span>{state.pendingRecommendation.actions[0]}<small>AI suggestion · awaiting your approval</small></span><button className="text-button" disabled={disable} onClick={()=>run('/api/instructor/recommendation/'+state.pendingRecommendation!.id+'/apply')}>Apply</button><button className="text-button" disabled={disable} onClick={()=>run('/api/instructor/recommendation/'+state.pendingRecommendation!.id+'/ignore')}>Ignore</button></>:<><span>{recent?.label||'Your room is ready'}{recent?.actor==='ai'&&<small>Changed by AI</small>}</span>{recent?.canUndo&&<button className="text-button" disabled={disable} onClick={()=>run('/api/instructor/undo',{action_id:recent.id})}>Undo</button>}</>}</div><button className="take-control" onClick={takeControl} disabled={takingControl}><Hand size={17}/>{takingControl?'Taking control…':'Take control'}</button></footer>
  </div>
 </div>
}
